### ISSUE TITLE
非常棒！有个需求不知道是否满足，自定义菜单，用户按权限加载菜单

### ISSUE THREAD

**Issue by ljb-2000** [neo1218/mana#14]
如：运维部，开发部，测试部， 运维部用户只能浏览运维部的菜单，如： /cmdb ， /system 等等。

**Comment by neo1218** [comment]
谢谢你的ISSUE！
这个需求不好实现，不是代码写不好，而是这里的权限不好定，因为每个用户对于权限都有不同的规划，如果我按照这个需求把权限划分的这么详细，那么别的使用mana的用户就不好搞了。因为每个人对权限的规划不同，所以mana只能笼统的划分权限。
我写mana的时候也一直在纠结这个问题，所以我全部用flask扩展来写，比如管理后台就是用flask-admin写的，这样你可以学习[flask-admin文档](http://flask-admin.readthedocs.org/en/latest/)，在原有的admin模块上添加自己想要的功能。
造轮子就是想做到通用，所以对于你的特定需求，还是建议你自己修改添加。
不过，还是感谢你提的ISSUE，谢谢😄
