### ISSUE TITLE
mana5.0计划: )

### ISSUE THREAD

**Issue by neo1218** [neo1218/mana#17]
> 目前mana只实现了我想法中基础＋进阶一点的地方。可以用了，而且做了一个产品。
### 1. 数据库编写:

能不能只在特定格式的文件中编写 [字段名] [字段类型] [关系] [字段属性] [其他] 然后扫描一遍就可以构建数据库, 也就是在ORM的基础上再进行一层封装。
### 2. 管理后台加强:

打算自己做一个加强版的管理后台，至少比flask-admin好用，这个需要考察
### 3. 部署:

如何使用mana进行一键部署、进程管理、或者给出样例让部署更加方便
### 4. 未来?

更新的特性？

mana 不是一个框架，有点像一个装饰器, 使用者只要编写核心代码， 这是最好的模式，当然会有一些限制，但是希望限制尽量少。

**Comment by neo1218** [comment]
关于数据库编写部分: 其实我后来想了想只在特定格式的文件中写其实不太灵活，的确可以把最基础的字段构建好， 但是比如我想做权限处理，做hash(token，验证)生成， 如果单纯格式的文本文件就没办法去写。所以数据库还是一定要用python代码写，而且还可以用sql语句去写，这是开发者自己决定的，mana不能决定。。。。。，，，，，，，，

**Comment by neo1218** [comment]
## mana 5.0 启动
1. 目录结构更改: 参照flask at scale
2. 方便的restful api generater
3. 提供flask工具箱: 常用装饰器，各种工具的实践总结
4. 部署命令
5. 加强版管理后台

**Comment by neo1218** [comment]
ship写好了, 这个礼拜业余时间推出mana5.0 !!!!

**Comment by raingolee** [comment]
3. 部署:

如何使用mana进行一键部署、进程管理、或者给出样例让部署更

---
这个不就是railgun了吗-。-

**Comment by neo1218** [comment]
@raingolee  我以为没人关注了😂

railgun是静态化的工具, 会build站点下所有的static(css, img, js), html 方便静态部署(不需要数据库)

而mana是一个初始化flask project的工具, 是为了中、大型项目快速搭建的, 里面会有数据库创建、管理后台、restful API初始化, 不过没有静态化😂
现在mana5.0的主要想法是和docker部署结合起来, 之前一直没有弄一键部署命令, 只有sql数据库、项目目录、蓝图和管理后台的初始化.

**Comment by raingolee** [comment]
恩，railgun和mana刚刚玩了下，挺方便的哈，感觉作者很用心，感谢提供这些好用的工具>.<

**Comment by neo1218** [comment]
@raingolee 还有很多不足的地方😂  ，填坑
